const projectsData = [
  {
    img: './image/python.png',          
    bgColor: 'linear-gradient(135deg, #3776ab 0%, #1e5799 100%)',
    title: 'Data Science With Python',
    desc: 'Comprehensive Data Science with Python',
    tags: ['Python', 'Anaconda development tool', 'Kaggle'],
    link: '#',
  },
  {
    img: './image/powerbi.png',        
    bgColor: 'linear-gradient(135deg, #f2c811 0%, #e6a800 100%)',
    title: 'Analytics Dashboard',
    desc: 'Interactive Power BI dashboard with real-time data visualization and insights',
    tags: ['Power BI', 'Power Apps', 'Data Analysis'],
    link: '#',
  },
  {
    img: './image/business-central.png', 
    bgColor: 'linear-gradient(135deg, #0078d4 0%, #005a9e 100%)',
    title: 'Business Central Solution',
    desc: 'Complete ERP implementation with custom modules for inventory and financial management',
    tags: ['Dynamics 365', 'AL Programming', '.NET'],
    link: '#',
  },
  {
    img: './image/selenium.png',        
    bgColor: 'linear-gradient(135deg, #43b02a 0%, #2d7a1c 100%)',
    title: 'Sauce Demo WebUI Testing',
    desc: 'Comprehensive WebUI testing for SauceDemo application to ensure functionality, reliability, and user experience',
    tags: ['Selenium', 'Java', 'TestNG', 'Maven'],
    link: '#',
  },
  {
    img: './image/react.png', 
    bgColor: 'linear-gradient(135deg, #61dafb 0%, #0099cc 100%)',
    title: 'React Developer',
    desc: 'Online Flower Booking Application for Celebration like Birthday, Ring Ceremony, Anniversary',
    tags: ['React', 'JavaScript', 'TypeScript', 'GitHub'],
    link: '#',
  },
]